### PR TITLE
Update LICENSE again

### PR DESCRIPTION
**Pull request by rnystrom**

### CODE REVIEW

**Comment by rnystromtest** [comment]
test

**Comment by rnystromtest** [comment]
another comment

**Comment by rnystrom** [comment]
bla bla bla

**Comment by rnystrom** [comment]
test test tests

**Comment by rnystromtest** [comment]
Comment

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystromtest** [comment]
Testing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
